### ISSUE TITLE
Drugs error

### ISSUE THREAD

**Issue by Jurre112** [ESX-Org/esx_drugs#100]
Error resuming coroutine: @esx_drugs/server/esx_drugs_sv.lua:734: attempt to index a nil value 
stack traceback: 
@esx_drugs/server/esx_drugs_sv.lua:734: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:169: in function <citizen:/scripting/lua/scheduler.lua:168> 
this is the error if we wanna collect drugs

**Comment by ElPumpo** [comment]
Update script
