### ISSUE TITLE
How to remove blips

### ISSUE THREAD

**Issue by huadgal** [ESX-Org/esx_drugs#101]
Hello, how i can remove  blips in esx_drugs 1.0.2

**Comment by Ness-Santana** [comment]
To delete de blips of the esx_drugs go to esx_drugs->client->mail.lua, and comment the line 143 of 171.
like this:

`--[[
function CreateBlipCircle(coords, text, radius, color, sprite)
	local blip = AddBlipForRadius(coords, radius)

	SetBlipHighDetail(blip, true)
	SetBlipColour(blip, 1)
	SetBlipAlpha (blip, 128)

	-- create a blip in the middle
	blip = AddBlipForCoord(coords)

	SetBlipHighDetail(blip, true)
	SetBlipSprite (blip, sprite)
	SetBlipScale  (blip, 1.0)
	SetBlipColour (blip, color)
	SetBlipAsShortRange(blip, true)

	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString(text)
	EndTextCommandSetBlipName(blip)
end


Citizen.CreateThread(function()
	for k,zone in pairs(Config.CircleZones) do

		CreateBlipCircle(zone.coords, zone.name, zone.radius, zone.color, zone.sprite)
	end
end)
--]]`
