### ISSUE TITLE
Errors in console Index value

### ISSUE THREAD

**Issue by Marcox360** [ESX-Org/esx_drugs#103]
`SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:50: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:226: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:226: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:50: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:99: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:50: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:226: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:50: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:275: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:226: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:450: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:226: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:50: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:329: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:50: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:504: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:50: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:226: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:226: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:226: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:153: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:50: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:402: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:450: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:504: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:50: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:226: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:275: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:450: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:153: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:504: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:504: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:504: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:329: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:329: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:329: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:153: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:504: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:504: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:329: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:153: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:504: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:329: attempt to index a nil value (local 'xPlayer')
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:504: attempt to index a nil value (local 'xPlayer')`

**Comment by caleb12345678** [comment]
i have this same problem how can i fix this
