### ISSUE TITLE
Issue with mysql

### ISSUE THREAD

**Issue by WantedManiac** [ESX-Org/esx_drugs#107]
USE `essentialmode`;

INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`) VALUES
	('seed_weed', 'Weed Seed', 100, 0, 1),
	('weed_unproc', 'Weed', 50, 0, 1),
	('weed_procc', 'Bagged Weed', 25, 0, 1),
	
	('seed_plant', 'Cocoa seed', 100, 0, 1),
	('cocainebase', 'Cocoa Leafs', 50, 0, 1),
	('cocainepaste', 'Cocaine Paste', 25, 0, 1),
	
	('seed_amphetamine', 'Chemical Mix', 100, 0, 1),
	('amphetamine_unprocessed', 'Amphetamine', 50, 0, 1),
	('meth_processed', 'Crystal Meth', 25, 0, 1),
	
	('seed_opium', 'Chemical Mixture', 100, 0, 1),
	('opium_unprocessed', 'Unprocessed Heroin', 50, 0, 1),
	('opium_processed', 'Heroin', 25, 0, 1)
;

This is what I have but it doesn't work and I can't figure out why

**Comment by scorpio686** [comment]
You do not use the right script ... https://github.com/ESX-Org/esx_drugs/blob/master/esx_drugs.sql
