### ISSUE TITLE
Problem for canCarryItem

### ISSUE THREAD

**Issue by Zombiefin1** [ESX-Org/esx_drugs#108]
Hello i have a problem

SCRIPT ERROR: @esx_drugs/server/main.lua:67: attempt to call a nil value (field ‘canCarryItem’)
TriggerServerCallback <@es_extended/server/functions.lua:33>
handler <@es_extended/server/common.lua:63>

Screenshot console: http://prntscr.com/ppcdp9
Screenshot file main.lua: http://prntscr.com/ppcdzx
Screenshot file official esx_drugs: http://prntscr.com/ppcezw
Screenshot file server.cfg :

http://prntscr.com/ppjxrw
http://prntscr.com/ppjy1e
http://prntscr.com/ppjy8r

Please help me

**Comment by ElPumpo** [comment]
update esx
