### ISSUE TITLE
Adding more options

### ISSUE THREAD

**Issue by Ex0r** [ESX-Org/esx_drugs#109]
The post on the fivem forums shows you can add other drugs fairly easily from the config file but neither the config or Client.lua seem to support anything other than weed. Actually there's a weed.lua file for the weed processing but no other drugs.

**Comment by JiminyKroket** [comment]
They are pretty easily implemented, if you'd like go check out esx_jk_drugs. I have archived it but if nothing else you can look through it

**Comment by LeoLight868** [comment]
@JiminyKroket  i tried that one with the new essentialmode, es_extened and other updated files. did not work for me. any advise?

**Comment by JiminyKroket** [comment]
You would have to convert it over from the old limit system to the new
weighted version

**Comment by LeoLight868** [comment]
I tried. i changed where it said 'limit' to 'weight'. I was only able to pick 1 coke up. then it said inventory full. @JiminyKroket
