### ISSUE TITLE
I can't collect drugs, attempt to compare nil with number.

### ISSUE THREAD

**Issue by rxbindotmp3** [ESX-Org/esx_drugs#122]
Hi, i can't collect drugs. I get this error in the console "SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:53: attempt to compare nil with number" and it's so sad because i can process it and sell but not collect. Please help me rly wanna get going with my server 👍 Thank you!
![1](https://user-images.githubusercontent.com/53920485/79626824-869d6a80-8133-11ea-8297-4a7e36e97ac8.PNG)
![2](https://user-images.githubusercontent.com/53920485/79626825-87360100-8133-11ea-8065-a8c3b30c863f.PNG)

I use version V1.0.2

**Comment by SloudPL** [comment]
I have to this error. Did you repair this?
