### ISSUE TITLE
i have this error with last update

### ISSUE THREAD

**Issue by funzik** [ESX-Org/esx_drugs#14]
[  10879375] Error running system event handling function for resource esx_drugs: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/esx_drugs_sv.lua:727: attempt to index a nil value (local 'xPlayer')
[  10879375] stack traceback:
[  10879375] 	server/esx_drugs_sv.lua:727: in upvalue 'handler'
[  10879390] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  10879390] stack traceback:
[  10879390] 	[C]: in function 'error'
[  10879406] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  10879406] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

**Comment by funzik** [comment]
[   1266625] Error running system event handling function for resource esx_drugs: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/esx_drugs_sv.lua:727: attempt to index a nil value (local 'xPlayer')
[   1266641] stack traceback:
[   1266641] 	server/esx_drugs_sv.lua:727: in upvalue 'handler'
[   1266656] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[   1266656] stack traceback:
[   1266656] 	[C]: in function 'error'
[   1266672] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[   1266672] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

**Comment by funzik** [comment]
[  79660796] Error running system event handling function for resource esx_drugs: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/esx_drugs_sv.lua:727: attempt to index a nil value (local 'xPlayer')
[  79660796] stack traceback:
[  79660812] 	server/esx_drugs_sv.lua:727: in upvalue 'handler'
[  79660812] 	citizen:/scripting/lua/scheduler.lua:163: in function <citizen:/scripting/lua/scheduler.lua:162>
[  79660812] stack traceback:
[  79660828] 	[C]: in function 'error'
[  79660828] 	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
[  79660828] 	citizen:/scripting/lua/scheduler.lua:162: in function <citizen:/scripting/lua/scheduler.lua:131>

**Comment by s0ig** [comment]
same error here

**Comment by funzik** [comment]
i have this error, do you know this problem ?

**Comment by funzik** [comment]
[  92089406] Error resuming coroutine: server/esx_drugs_sv.lua:221: attempt to index a nil value (local 'xPlayer')
[  92089421] stack traceback:
[  92089437] 	server/esx_drugs_sv.lua:221: in function <server/esx_drugs_sv.lua:215>

**Comment by JaroSound** [comment]
Same here sometimes.

**Comment by ElPumpo** [comment]
This is because the player is leaving the zone / the source is not there. Do a check if `source` is nil will fix the problem
