### ISSUE TITLE
Money Bug

### ISSUE THREAD

**Issue by Vanheden** [ESX-Org/esx_drugs#18]
There is a bug where you can manipulate the drug interaction zones to add, process & sell more than one at a time its basically where u go in and out of the zone pressing e and it will make the drug circle do the event more than once at a time

and you can sell multi times spam E

**Comment by JaroSound** [comment]
same for me :(

**Comment by Jukeboxrp** [comment]
in client an then esx_drugs_cl change wait from "0" to "10000" to set 10 sec delay on markers. It will be impossible to bug it then. Thats what I did. Works good.


-- Activate menu when player is inside marker
Citizen.CreateThread(function()
    while true do

        Wait(0)

**Comment by Vanheden** [comment]
Gonna try it out!
