### ISSUE TITLE
user gets stuck if attempting to open phone

### ISSUE THREAD

**Issue by Jhudri** [ESX-Org/esx_drugs#26]
if your in the zone and have your users frozen, if they try to open the phone it will lock them up to the point they have to relog.

**Comment by ElPumpo** [comment]
Can be fixed very easily by just disabling the action key

**Comment by JaroSound** [comment]
When someone is in zone and the phone rings, he can not do anything and the sound is ON all the time.
I dont think disabling action key fix this....

**Comment by JaroSound** [comment]
Any fix yet?

**Comment by benzon** [comment]
Easy to fix

Line 42: ESX.UI.Menu.CloseAll() <-- This is the issue messing with phone, inventory everything :)

If this is removed you can check inventory etc.

**Comment by ElPumpo** [comment]
`ESX.UI.Menu.CloseAll()` doesn't properly close the phone?

**Comment by JaroSound** [comment]
But on only phone is the problem... The entire esx menu is

**Comment by JaroSound** [comment]
Removing ESX.UI.Menu.CloseAll() from esx_drugs Client do the trick.
