### ISSUE TITLE
Console error during character creation for esx

### ISSUE THREAD

**Issue by PhilipBernhardsson** [ESX-Org/esx_drugs#40]
Error running system event handling function for resource esx_drugs: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/esx_drugs_sv.lua:734: attempt to index a nil value (local 'xPlayer')
stack traceback:
	server/esx_drugs_sv.lua:734: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

**Comment by Jeffrey-Lang** [comment]
what you could do to improve the script is whenever you call a xPlayer.something
before that check if the xPlayer is not nil
so

```
if xPlayer ~= nil then
--your code here
end
```
