### ISSUE TITLE
Alpha Feedback..

### ISSUE THREAD

**Issue by JEStudios** [ESX-Org/esx_drugs#51]
First off love it great work, just wanted to provide what I found from it ... I was able to spam E on the pick up to get about 15 weed not sure if that is supposed to be a thing for sure. Then for some reason I fell thru the map but that could be my side. Again I know its in Alpha just wanted to provide info

**Comment by ElPumpo** [comment]
The E spam thing was fixed in https://github.com/ESX-Org/esx_drugs/commit/7035ed026191cac9e753ac031c2c2358ae1045d1, the other issue you had cannot be due to this resource.

thanks for your input!

**Comment by JEStudios** [comment]
I figured , thanks :) again love the new verison
