### ISSUE TITLE
Optimize spawn

### ISSUE THREAD

**Issue by Mahlster** [ESX-Org/esx_drugs#56]
You did a very good job with the random points of the plants. But the random points requires a lot of resources for the server (es_estended), would it be possible to delete random points and replace it with fixed points ?

Ex : The plants appear on predefined points and reappear after several seconds.

Thank you very much for taking the time to read this message

**Comment by ElPumpo** [comment]
Uuum what? Fixed points sounds like an awful idea, do it yourself if you want that. Optimization??
