### ISSUE TITLE
Can't sell drugs

### ISSUE THREAD

**Issue by MrAdapt** [ESX-Org/esx_drugs#61]
Unable to sell drugs to the drug dealer, we can gather the weed, process it, but when we "Talk to drug dealer" nothing happens, there is no drug dealer npc nor menu that pops up when we press E to talk to him, anyway to fix this?

**Comment by ElPumpo** [comment]
99% you are running an old version of ESX

**Comment by pavelorio** [comment]
I have the same problem,i can't sell drougs....
