### ISSUE TITLE
I get this error something with math

### ISSUE THREAD

**Issue by krrx** [ESX-Org/esx_drugs#67]
https://github.com/ESX-Org/esx_drugs/blob/7974aea5a1c491ac44a2ca3648d6357410e0bdeb/client/main.lua#L68

**Comment by krrx** [comment]
![image](https://user-images.githubusercontent.com/39865270/50524117-2e70ce00-0ad4-11e9-961f-a5103aebff04.png)

**Comment by Santagain** [comment]
Update your ESX Version

**Comment by ElPumpo** [comment]
then update esx dummy
