### ISSUE TITLE
Drugs missing

### ISSUE THREAD

**Issue by Valkatastz** [ESX-Org/esx_drugs#69]
That's not exactly a bug related but a question / suggestion. Will you add the rest of the drugs like opium,coke,meth or should the players do it all by themselves? At the current state, it comes with the weed only. I would be willing to make the rest if you are too busy on the rest of the ESX package.

**Comment by ElPumpo** [comment]
For now there will only be weed. More drugs are not fit for 32 player servers, but we will implement coke when onesync arrives.
