### ISSUE TITLE
Error running call reference function for resource esx_drugs

### ISSUE THREAD

**Issue by marknx** [ESX-Org/esx_drugs#87]
> Error running call reference function for resource esx_drugs: citizen:/scripting/lua/scheduler.lua:403: server/main.lua:71: attempt to index a nil value (local 'xItem') 

stack traceback: 
server/main.lua:71: in upvalue 'ref' 
citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388> 
[C]: in function 'xpcall' 
citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372> 
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow' 
citizen:/scripting/lua/MessagePack.lua:465: in field 'any' 
citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack' 
citizen:/scripting/lua/scheduler.lua:626: in field '?' 
server/functions.lua:33: in field 'TriggerServerCallback' 
server/common.lua:88: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218> 
stack traceback: 
[C]: in function 'error'

**Comment by marknx** [comment]
everything updated, i get this error when i try to harvest a plant

Any ideas?
Thanks for your time !

**Comment by ElPumpo** [comment]
Rerun sql
