### ISSUE TITLE
cant collect drugs

### ISSUE THREAD

**Issue by TakuyaSan420** [ESX-Org/esx_drugs#88]
Hello im using an older Version of esx_drugs but i cant collect any drugs. Not weed, meth, opium and the others.. there is just no pop up for me
Thanks for the help

**Comment by 14520614** [comment]
have you fix it @TakuyaSan420

**Comment by TakuyaSan420** [comment]
Yes kind off. not fully. still working on it. but its not important atm

**Comment by 14520614** [comment]
Error running call reference function for resource esx_drugs: citizen:/scripting/lua/scheduler.lua:405: @esx_drugs/server/main.lua:71: attempt to index a nil value (local 'xItem') 

I stuck this error when try to harvest :v do you have same error ?

**Comment by ElPumpo** [comment]
Update your items table

**Comment by Havoc1031** [comment]
SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:565: attempt to compare nil with number

Any fix for this heres my error

**Comment by rxbindotmp3** [comment]
that's my problem too @Havoc1031
