### ISSUE TITLE
More drugs

### ISSUE THREAD

**Issue by Valkatastz** [ESX-Org/esx_drugs#90]
It's not a bug related. However, do you plan to release anytime soon the rest of the drugs? Because you have limited it to weed only atm. As far as I can remember, you said you will do it once 64 player slot are released. Well, FiveM already released 64 player slots and almost every server is on OneSync now. Just for information, old version where you have all the drugs are working perfectly and I don't see why you still don't implement them into the new version.

**Comment by ElPumpo** [comment]
Yes maybe some day.. I just dont fully know how to implement them (lack of ideas). I dont wanna make then copy&paste from new shiny weed code
