### ISSUE TITLE
weed processing not working 

### ISSUE THREAD

**Issue by Danu034** [ESX-Org/esx_drugs#97]
when i do the weed processing  i get this error 

Error running call reference function for resource esx_drugs: citizen:/scripting/lua/scheduler.lua:355: @esx_drugs/server/main.lua:87: attempt to index a nil value (local 'xMarijuana')
stack traceback:
        @esx_drugs/server/main.lua:87: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:341: in function <citizen:/scripting/lua/scheduler.lua:340>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:340: in function <citizen:/scripting/lua/scheduler.lua:339>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:355: in function <citizen:/scripting/lua/scheduler.lua:324>
Error resuming coroutine: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:578: in upvalue 'cb'
     a:14: in function <@es_extended/server/functions.lua:10>

**Comment by ElPumpo** [comment]
Insert sql
