### ISSUE TITLE
ERROR SCRIPT ERROR: @esx_drugs/server/esx_drugs_sv.lua:734: attempt to index a nil value

### ISSUE THREAD

**Issue by podubcity** [ESX-Org/esx_drugs#99]
hello everyone when i try to put the esx_drugs i get an error in the game passing the point is this for all the drugs.

![image](https://user-images.githubusercontent.com/53730226/62854699-5e31b680-bcf0-11e9-9b24-486b08bea613.png)

**Comment by ElPumpo** [comment]
Old code
